[machine]

#====================================================================================================================================
# IBM PC/XT
#====================================================================================================================================

[machine.ibm_xt]

video = "cga"
postcard = false

[[machine.ibm_xt.rom]]

filename = "GLABIOS_0.8b0_8T.ROM"
addr = 0xFE000

[machine.ibm_xt.hdc]

controller = "st506"
hdd_count = 1

[[machine.ibm_xt.hdc.hdd]]

geometry = "615/4/17"

[[machine.ibm_xt.hdc.hdd]]

geometry = "615/4/17"

#====================================================================================================================================
# Input System.
#====================================================================================================================================

[input]

[input.ignore_keys]
"key:escape" = true
"key:tab" = true
"key:f1" = true
"key:f2" = true
"key:f3" = true
"key:f4" = true
"key:f5" = true
"key:f6" = true
"key:f7" = true
"key:f8" = true
"key:f9" = true
"key:f10" = true

#====================================================================================================================================
# Misc.
#====================================================================================================================================

[misc]

tps = 20

#====================================================================================================================================
# Debug.
#====================================================================================================================================

[debug]

show_fps = false
